### ISSUE TITLE
Cache is not used

### ISSUE THREAD

**Issue by salvapatuel** [derekhe/xplane-map-enhancement-release#10]
Flying always on the same area and the cache is never used.

![Screenshot 2024-03-30 125401](https://github.com/derekhe/xplane-map-enhancement-release/assets/72168990/415320d6-bc83-4009-8fb5-8829774463c3)

**Comment by derekhe** [comment]
Thanks for reporting, I'm investigating.

**Comment by derekhe** [comment]
Fixed in v1.0
