### ISSUE TITLE
Reached max entry

### ISSUE THREAD

**Issue by satyr213** [derekhe/xplane-map-enhancement-release#13]
![изображение](https://github.com/derekhe/xplane-map-enhancement-release/assets/166120347/c4212975-aa3e-4fe6-a3c6-dd5974db5678)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#734-troubleshooting-backend-server-error

**Comment by satyr213** [comment]
Thank you

**Comment by rtc79clm** [comment]
I am getting the same message: Reached max entry

**Comment by satyr213** [comment]
![Uploading изображение.png…]()

**Comment by derekhe** [comment]
Try install the two packages:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.4-windows-x64-installer
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-8.0.4-windows-x64-installer
