### ISSUE TITLE
RJTT RWY05 underwater

### ISSUE THREAD

**Issue by UmiAkai** [derekhe/xplane-map-enhancement-release#16]
**Required:**

* **Title:** Briefly describe the bug.
* **Description:** What did you expect? What happened instead? (Include screenshots/recordings if possible)
* RJTT RWY05 underwater
* **Version:** (If applicable)
* 1.0.1
* **Platform:** (If applicable)
* xp12.0.9
* **Screenshots:** (If applicable)
* ![Screenshot 2024-04-13 10-43-15](https://github.com/derekhe/xplane-map-enhancement-release/assets/94544030/132fedfa-6f46-4882-9a9a-deae1c38f411)

**Optional:**

* Any additional helpful information.
* Seems also be a knows issue in Autoortho as well with fix:
  https://forums.x-plane.org/index.php?/forums/topic/302252-rjtt-runway-0523-partially-in-water/

**Note:** This is for bug reports only. For general feedback, use the [appropriate channel].

**Thank you for your help!**

**---**

**Tips:**

* Be clear and concise.
* Be specific about steps and behavior.
* Check for existing issues before reporting new ones.

Following these guidelines helps us fix bugs faster.

**Comment by derekhe** [comment]
Thanks for reporting, I will update it later.

**Comment by derekhe** [comment]
I merged the fix into the latest package, but it seems the bridge between the two runways is not there. Please check.

**Comment by UmiAkai** [comment]
It seems more part of the foundation in the west part been underwater.

**Comment by derekhe** [comment]
Yes, it still but it is ok to drive into that area. I will have a look how to fix it in future.
