### ISSUE TITLE
Loading extremely slow.

### ISSUE THREAD

**Issue by cyril84** [derekhe/xplane-map-enhancement-release#17]
* **Platform:** X-Plane 12
* **Computer specification:**

Hello, I'm on X-Plane 12 and I have a pro license valid for 6 months. Unfortunately, I can't use it because of a problem loading orthophotos. No matter which image provider I use, the application generally takes 18 minutes to load between 10 and 20,000 orthophotos, instead of the usual 2 minutes. While I'm writing this message, in 5 minutes, it has loaded exactly 2594 images. I made an exception with my antivirus by adding exclusions for both download and cache folders, and I also made exclusions in my firewall to allow the application without any problems. In terms of image quality, I'm even in medium mode and I've checked the 'fastload' option. And I have completely uninstalled Auto Ortho to avoid conflicts. I don't know what else to do, especially since the application works fine on MSF (Microsoft Flight Simulator), but it's very, very slow on X-Plane 12. I should note that I have read the entire FAQ, but nothing seems to solve the problem. What I find strange is that when loading the same scene twice, the loading time remains the same (18 minutes), as if no cache is being applied
P.S: I also specify that I have a 2GBS fiber connection.
Thank you for your help!

**Comment by derekhe** [comment]
What's the deviceid in the license page and your cpu and ram config.

**Comment by cyril84** [comment]
Hello and thank you for your speed and professionalism. For your information, here is my current setup.
============================
Processeur: Intel I7 13700K
Mémoire: DDR5 Corsair Vengeance - 32 Go (2 x 16 Go) 5600 MHz - CAS 36
Carte graphique: Gainward RTX 3080TI Phoenix 12Go,
Carte mère: GIGABYTE B760 GAMING X
Crucial CT2000P5PSSD8 SSD Interne P5 Plus 2To (PCIe 4.0, 3D NAND, NVMe, M.2) jusqu'à 6600Mo/s pour X-plane 11, MSF20 et Windows 10
SSD 525 Go Crucial MX300 pour les tuiles Ortho
Stockage total 16 to pour les tuiles Ortho
1 écrans Asus 27 3d +. 1 écran 27 1440P IIYama
====================================
And I found where the problem was coming from, I will explain it to you so as not to have wasted your time. The files are mounted on an external hard drive with an NVMe disk. And this latter, instead of being connected to a USB 3 port, was connected to a USB 2 port, hence the slowness. I will also be doing a video review of your application on my channel and I will not fail to mention your speed in support and your professionalism. However, what bothers me is that the video should be released at the beginning of the month but viewers will not be able to take advantage of the 20% discount on the pro version. Would it be possible for you to extend this promotion beyond the end of April or to obtain a promo code that I could provide during the video?
Best regards, Cyril Benoît.
https://www.youtube.com/c/furax84

**Comment by cyril84** [comment]
Thanks anyway, but can you extend the promo?
Best regards

**Comment by derekhe** [comment]
When is the release date of the video?

**Comment by cyril84** [comment]
I'm going to make it next week and release it around May 4th.
