### ISSUE TITLE
Eror 500

### ISSUE THREAD

**Issue by Pr0beel** [derekhe/xplane-map-enhancement-release#18]
![изображение_2024-04-25_221427989](https://github.com/derekhe/xplane-map-enhancement-release/assets/166286008/561794f2-bf08-42d9-9fbf-1f26cb5306a2)
Hey, everybody. 
I have a problem
I downloaded version 1.0.2 and I got an error that I can't solve. I reinstalled and rolled the version back to 1.0.1 but the error is still there. I restarted the pc but it didn't help either. I will be very glad if someone can help me to solve the problem.

**Comment by derekhe** [comment]
Please provide the device id in the license page.
