### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by dev1c3** [derekhe/xplane-map-enhancement-release#2]
* **Description:** When I completed everything in the manual I wanted to start the app, so I can get it running and press start but instead of it starting I get this message(The server start failed. Reason: Image cache folder not found
For more information, please visit the [FAQ page](https://github.com/derekhe/xplane-map-enhancement-release/wiki/FAQ).)
* **Version:** 0.0.100
* **Platform:** PC
* **Computer specification:** Ryzen 9 6900HX, Rtx 3070Ti, 32Gb DDR5
* **Screenshots:** 
![Screenshot 2024-02-24 202044](https://github.com/derekhe/xplane-map-enhancement-release/assets/95092962/134eca50-aa64-48ed-92cb-c8ae9bdcd47c)

* **Log file:** (Default: C:\Program Files\X-Plane Map Enhancement\resources\core\release\logs): 
[log20240224.txt](https://github.com/derekhe/xplane-map-enhancement-release/files/14394181/log20240224.txt)

**Comment by derekhe** [comment]
Hello, I think you missed a setting: 
![image](https://github.com/derekhe/xplane-map-enhancement-release/assets/1734077/43150bd6-d783-4514-a86a-209dbab43dde)
It should like this: 
![image](https://github.com/derekhe/xplane-map-enhancement-release/assets/1734077/d137ed0b-2b98-48b0-bc7f-139380410b1e)

**Comment by dev1c3** [comment]
Sry for that;)

нд, 25 лют. 2024 р. о 03:02 hesicong ***@***.***> пише:

**Comment by derekhe** [comment]
Nws, I will close this now.
