### ISSUE TITLE
Incredibly high memory utilization

### ISSUE THREAD

**Issue by ImPlasmaTbh** [derekhe/xplane-map-enhancement-release#21]
## Beta Testing Bug Feedback

**Help us improve!** Report bugs you encounter using this template:

**Required:**

* **Title:** Briefly describe the bug.
The program uses a lot of memory randomly.
* **Description:** What did you expect? What happened instead? (Include screenshots/recordings if possible)
The program should use around 6 gigabytes of RAM with memory optimization enabled in settings.
Expected result: program uses 5-8 gigabytes of RAM 
What actually happened: program fluctuates between 2 gigabytes and 16 gigabytes of ram. Usually hovers around 5-8 gigabytes of RAM till it somehow momtentarily exceeds 12-13 gigabytes of RAM sometimes and makes me hit 100% memory utilization. When the program uses more than 12 gigabytes of RAM and my system hits 100% memory utilization, the program memory on task manager reports 2-3 gigabytes of RAM usage whilst I encounter temporary performance degradation.
* **Version:** (If applicable)
1.0.3 stable
* **Platform:** (If applicable)
Windows 11
* **Computer specification:**
7900X3D, 6800XT, 16x2 GB DDR5 6000CL30 RAM, X-Plane and program files installed on same 1 TB NVMe SSD
* **Screenshots:** (If applicable)
![image](https://github.com/derekhe/xplane-map-enhancement-release/assets/46997381/9063405f-775f-4840-b393-5fccf540656c)
* **Log file:** (Default: C:\Program Files\X-Plane Map Enhancement\resources\core\release\logs):

**Optional:**

* Any additional helpful information.

**Note:** This is for bug reports only. For general feedback, use the [appropriate channel].

**Thank you for your help!**

**---**

**Tips:**

* Be clear and concise.
* Be specific about steps and behavior.
* Check for existing issues before reporting new ones.

Following these guidelines helps us fix bugs faster.

**Comment by derekhe** [comment]
Sure, I've noticed this issue and find a way to improve it.
