### ISSUE TITLE
Windows is searching for Errors on items that get put into the X-Plane Scenery Folder

### ISSUE THREAD

**Issue by jonesm35205** [derekhe/xplane-map-enhancement-release#26]
I have seen one person report this without a fix.    As you can see by the screen shots I have only North America installed into my Base Packages Folder.   But after Map Enhancement is started it will search for every one of one of the regions (including the overlay) that I didn't download, don't want to download at this time when X-Plane 12 is started up.  Hence the Browse messages for each one when X-Plane is started up and annoying.   It is putting those items that I haven't downloaded in the X-Plane 12 Scenery folder, not sure but am thinking that is most likely the issue and why its looking for it and giving the browse messages.   Please look into and correct.   

Thank You,   Mark

Screen shots attached.

[4 Screenshots For Map Enhancement Doc and Issues.zip](https://github.com/user-attachments/files/15855521/4.Screenshots.For.Map.Enhancement.Doc.and.Issues.zip)

**Comment by derekhe** [comment]
Please try latest version.
