### ISSUE TITLE
Endless Loading

### ISSUE THREAD

**Issue by emmanuelgemini** [derekhe/xplane-map-enhancement-release#27]
## Bug Feedback

**Help us improve!** Report bugs you encounter using this template:

**Required:**

* **Title:** App just keeps processing and downloading textures, Sim refuses to load.
* **Description:** The app just keeps downloading and loading tiles and the sim just refuses boot as a result. The screenshot is just one sample, I've seen it reach over 220,000 loaded, and over 6GB. I have tried restarting XPlane multiple times and tested Bing, Google and ArcGIS, same results. Based on the help documents, it says, the expected number should be between 10,000 to 50,000 loaded, so I would assume there is something going wrong here. 

* **Advanced Settings:** (in case it might help)
Quality: medium
Timeout: Default 30
Max Connections: Default 200
Fast Load; OFF (But I have tried with fast load on, same results)
Memory Optimization: On

* **Version:** App version 1.0.5, Xplane 12.1 beta
* **Platform:** Windows
* **Computer specification:** Ryzen 5700x, RTX 3070, 32GB ram
* **Screenshots:** 

![Screenshot 2024-06-17 090513](https://github.com/derekhe/xplane-map-enhancement-release/assets/10252957/cc8e2553-6271-49ed-88f1-f03e0d0c0259)

**Comment by derekhe** [comment]
You can try remove some plugins and mods see if it is better. How about change to another airport (maybe try different country).
Please give me your device id in the license page as well.





------------------ Original ------------------
From: emmanuelgemini ***@***.***&gt;
Date: Mon,Jun 17,2024 9:17 AM
To: derekhe/xplane-map-enhancement-release ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/xplane-map-enhancement-release] Endless Loading (Issue #27)





 
Bug Feedback
 
Help us improve! Report bugs you encounter using this template:
 
Required:
  
 
Title: App just keeps processing and downloading textures, Sim refuses to load.
 
 
 
Description: The app just keeps downloading and loading tiles and the sim just refuses boot as a result. The screenshot is just one sample, I've seen it reach over 220,000 loaded, and over 6GB. I have tried restarting XPlane multiple times and tested Bing, Google and ArcGIS, same results. Based on the help documents, it says, the expected number should be between 10,000 to 50,000 loaded, so I would assume there is something going wrong here.
 
 
 
Advanced Settings: (in case it might help)
 Quality: medium
 Timeout: Default 30
 Max Connections: Default 200
 Fast Load; OFF (But I have tried with fast load on, same results)
 Memory Optimization: On
 
 
 
Version: App version 1.0.5, Xplane 12.1 beta
 
 
 
Platform: Windows
 
 
 
Computer specification: Ryzen 5700x, RTX 3070, 32GB ram
 
 
 
Screenshots:
 
  
Screenshot.2024-06-17.090513.png (view on web)

**Comment by emmanuelgemini** [comment]
Done a couple of flights after updating to the most recent 1.1.2 and the new base files. I have no longer seen this scenario occur (at least for now). At the moment, the sim is now loading reliably. Will do a couple more test flights in different regions to further test,
