### ISSUE TITLE
Simplify Base Package Installation

### ISSUE THREAD

**Issue by Fragtality** [derekhe/xplane-map-enhancement-release#28]
## Bug Feedback

**Help us improve!** Report bugs you encounter using this template:

**Required:**

* **Title:** Simplify Base Package Installation.
* **Description:** Expected: simplified Base Package Installation with V2. Instead: Same labour-intensive/manual Approach.
* **Version:** v1.1.0
* **Platform:** Windows
* **Computer specification:** N/A
* **Screenshots:** N/A

**Optional:**
The current Approach for Base Package Installation just isn't State-of-the-Art and doesn't really fit to the general Usability of the Program itself (i.e. it has an Installer, the Installer takes care of the Requirements, you can simply click and run).
It just something that could be easily done in an automated Fashion by a Script or the Program itself (I'd see it in the GUI - after updating/selecting the Base-Folder, the Program will check if the Files are there, and if not download->extract in the Background). Could be also further enhanced with a Version-Check, i.e. the Repository having a File listing the Base-Package-Files and their current Version where the Program could check the local Files against.
I know myself that such User-Experience Improvements can be Time consuming, i.e. stealing Time from the "actual work". But I just feel that the Base-Package Installation doesn't really fit to what XME tries to achieve. I mean People want Ortho-Imaginary with no Fuzz, but in Order to get XME running you need to handle GB's of Scenery-Files first 😅 

**Note:** This is for bug reports only. For general feedback, use the [appropriate channel].
I'd love to use the [appropriate channel] - if that would have been named 😉  

**Thank you for your help!**

**---**

**Tips:**

* Be clear and concise.
* Be specific about steps and behavior.
* Check for existing issues before reporting new ones.

Following these guidelines helps us fix bugs faster.

**Comment by derekhe** [comment]
Yes, it is on the way.

**Comment by Stoned84** [comment]
Really it is such a pain to re download base packages they fail all the time,you seem to assume that people should download all the packages ,so why so complicate?? Dude make a torrent file for all the packages ..shit it take ages to get it right ..this is not freeware!

**Comment by Stoned84** [comment]
This all thing should come as a bundle.....come on make it us ,especially if you charge people as a service make it a torrent bundle or whatsoever ,clean up the all thing it takes ages to get it right.
Simplify the all process especially when you have so many updates.

**Comment by filipchudoba** [comment]
Yep, torrent would be awesome, it is super simple to set it up. Or if it could be implemented directly, that would be even better.

**Comment by Fragtality** [comment]
Imho, Torrents wouldn't be a good Solution:
1. I find it questionable if a Torrent Downloader is easier to implement than a simple Routine of http-download File, check Hash and Extract/Combine.
2. If it was meant to be easy on the User-Side to setup a BitTorrent Client: It wouldn't really improve the Situation if you would have to setup a Filesharing Client before you can use XME.
3. On both Variants: There would still be a Server required (which I just assume as something "not free") which is currently not needed (because hosted on Github).
4. On both Variants: Downloads with a BitTorrent Client could be more problematic than a simple HTTP(s)-Download. (i.e. some People having an ISP which is hard against Filesharing or connect via VPN which does not allow that Protocol)

An Alternative: Yes. The only Way to download the Base-Package: No.

**Comment by DH3nr1** [comment]
Hello,
Would it be possible to get another way to get these base packagses? I was downloading them for a 2 days straight now :( I know i don't have a good internet here, but everything else is downloading at least 10MBits/S but these base package was downloading by 100kbits/s :(

**Comment by derekhe** [comment]
@filipchudoba there is a downloader in v2 version, please have a try.

**Comment by derekhe** [comment]
> Hello, Would it be possible to get another way to get these base packagses? I was downloading them for a 2 days straight now :( I know i don't have a good internet here, but everything else is downloading at least 10MBits/S but these base package was downloading by 100kbits/s :(

The files are available on GitHub and should work well in countries outside of China. Alternatively, you can use download tools to access them.

**Comment by Fragtality** [comment]
Working as expected - Thank you! 😃
