### ISSUE TITLE
No data received from XPlane, stopping connector

### ISSUE THREAD

**Issue by CHHHQ** [derekhe/xplane-map-enhancement-release#3]
完全按照要求安装基础包和软件，先打开map enhancement，后打开游戏，游戏可以正常进入，但为默认地景。与此同时软件一直显示如下界面，没有下载任何区块
![image](https://github.com/derekhe/xplane-map-enhancement-release/assets/109466809/35fd4551-4df4-4f24-a335-0bee8e5cbbe6)

log中一直显示
[INF] XPlane process detected, starting connector
[WRN] No data received from XPlane, stopping connector
[log20240301.txt](https://github.com/derekhe/xplane-map-enhancement-release/files/14461235/log20240301.txt)

**Comment by djlaui** [comment]
For me too , not work
