### ISSUE TITLE
Server Start Failed

### ISSUE THREAD

**Issue by magentilized** [derekhe/xplane-map-enhancement-release#35]
So I have this Problem

I am currently using the Free version of XP Map Enhancement (latest) and i get this message when I start up XPME. Can anybody explain what this means and how I can fix it?
![r43qt453qw](https://github.com/derekhe/xplane-map-enhancement-release/assets/137439772/36e122c3-dc06-463d-a659-a3ed78567a28)

**Comment by derekhe** [comment]
Please follow the readme and download all the base packages

**Comment by magentilized** [comment]
> Please follow the readme and download all the base packages

All the base packages are downloaded already and I followed the Instructions in the User Manual. I reinstalled XPME and im met with new problems:
First off, when I wanted to merge the z_ao_eur files with the .exe file, i got this message "ERROR: the restored file's contents differs from the original one; the piece might be corrupted." in the gSplit program. I still ended up with a normal VHD file for europe. FYI I didnt have problems with the overlay files. 
As I reconfigured all my Paths and stuff in XPME 1.1.3 I wanted to start XPME (Bing) however I was met with this message: "Start error
Server start failed. Please refer to the user manual for correct setup. [Click here to read user manual](https://github.com/derekhe/xplane-map-enhancement-release/wiki/FAQ)
Error mounting VHD files. Please make sure Virtual Disk service is enabled. Err: One or more errors occurred. (Mount failed: Not Supported Activity ID: {58f9647f-155f-4ba6-82d0-ca6774fb9eaa}) (Mount failed: Not Supported Activity ID: {d08c8884-1c60-40df-8b9b-687ae00bca8e})". I set Virtual Disk service to automatic btw.

Help would be appreciated,

Sincerely,
M

**Comment by derekhe** [comment]
The file you downloaded may be corrupted, which could explain why gsplit is reporting errors.
