### ISSUE TITLE
Application endless loading after prssing "START"

### ISSUE THREAD

**Issue by PhilippeTORNE** [derekhe/xplane-map-enhancement-release#36]
Hello,

Whatever the map selected, I often have the application unable to load after pressing "START". I need to retry several hours or days ofter and it works again. Running the application in administrator. Screenshot attached

Regards
![Capture d’écran (305)](https://github.com/user-attachments/assets/ef0169a3-9dc2-470f-9b32-b33be4cab601)

**Comment by derekhe** [comment]
What's the device id in the license page?

**Comment by PhilippeTORNE** [comment]
Is it safe to post this kind of information ? I noticed that if I start the application WITHOUT admin rights it start fine. Maybe my mistake but I remember reading it has to be started with admin rights ? Maybe I mistake with MSFS Map Enhancement which I also use ?

**Comment by derekhe** [comment]
Please try v2 version. The device id on the license page has no personal information, it is just an identifier for the application.
