### ISSUE TITLE
Version 1.1.3 always creates a new shortcut

### ISSUE THREAD

**Issue by PhilippeTORNE** [derekhe/xplane-map-enhancement-release#38]
Hello,

Version 1.1.3 always creates a new shortcut called "yAutoOrtho_Overlays" in my Custom Scenery folder despite I removed this folder after 1.1.0 installation following the instructions. Everytime I delete the shortcut in my Custom Scenery folder but the application always creates a new one and I get this missing shortcut message when starting XP (screenshot attached). Could you please do something for future version do not create this shortcut anymore ?

![Capture d’écran (306)](https://github.com/user-attachments/assets/755f98ab-df8a-45a1-ba78-e9c92c42e348)

**Comment by derekhe** [comment]
Sure, will fix this in next version.

**Comment by PhilippeTORNE** [comment]
Thanks a lot

**Comment by derekhe** [comment]
Please try v2 version, this should be fixed.

**Comment by PhilippeTORNE** [comment]
Thanks for the update I will try it ASAP
