### ISSUE TITLE
Cache Option Disregarded

### ISSUE THREAD

**Issue by adanulea** [derekhe/xplane-map-enhancement-release#39]
On the 2.0 latest version (and older versions) - the cache never stops growing. On long hauls, it becomes untenable. 

Also, on 2.0 unlike previous version, the Delete Cache button does not work live when app running. 

![Screenshot 2024-07-29 170133](https://github.com/user-attachments/assets/4500819a-844a-4d74-9b25-00798a5199f8)

**Comment by derekhe** [comment]
I will investigate.

**Comment by adanulea** [comment]
Just to add to this, both 2.0 versions (MSFS and XP), do not remember the dark/light theme when reopening. They always open in dark mode irrespective of previous use.

**Comment by derekhe** [comment]
> Just to add to this, both 2.0 versions (MSFS and XP), do not remember the dark/light theme when reopening. They always open in dark mode irrespective of previous use.

Fixed, please have a try. And the cache issue is also fixed.
