### ISSUE TITLE
Settings are not save in V2.0.0.0 (PRO)

### ISSUE THREAD

**Issue by levelupsim** [derekhe/xplane-map-enhancement-release#40]
Derek, thank you very much for uploading the new version for X-Plane 12, I just want to report that the settings we make are not saved, after closing and opening the program everything goes back to default.

Version 2.0.0.0 PRO
Windows 10x64

Please check this issue!
Thanks!

**Comment by derekhe** [comment]
Could you provide your device id on the license page? I will investigate.

**Comment by levelupsim** [comment]
> Ok, I fixed this issue in 2.0.1 please have a look

the problem with saving options has been solved, you are fast! thanks and please keep looking into this and updating this program, we xp12 users need this solution, thanks!
