### ISSUE TITLE
Welcome to xplane-map-enhancement-release Discussions!

### ISSUE THREAD

**Issue by abhovi** [derekhe/xplane-map-enhancement-release#41]
### Discussed in https://github.com/derekhe/xplane-map-enhancement-release/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **derekhe** February 23, 2024</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by abhovi** [comment]
Hello,
I fly both with MSFS2020 and with X-Plane. With the former the program works great. But when I download the X-Plane version I get an error message the moment I open the file: Unable to execute file in the temporary directory. Setup aborted. Error 5:  Toegang geweigerd (access denied).
What do I wrong? I have Autoortho 7.2 installed, but the program takes a quarter of an hour every time I start up, so I am looking for something faster.

**Comment by derekhe** [comment]
> Hello, I fly both with MSFS2020 and with X-Plane. With the former the program works great. But when I download the X-Plane version I get an error message the moment I open the file: Unable to execute file in the temporary directory. Setup aborted. Error 5: Toegang geweigerd (access denied). What do I wrong? I have Autoortho 7.2 installed, but the program takes a quarter of an hour every time I start up, so I am looking for something faster.

Which xplane version are you using? The latest v2 works well. And it can work in parallel with msfs v8 version.
From your error message, maybe you installed into a wrong folder?

**Comment by abhovi** [comment]
Thank you for your answer.
I use X-Plane 12 recently updated.
I probably installed the installer in a wrong folder. I simply thied to install from the download section of my computer. Is there a preferred folder?

**Comment by derekhe** [comment]
Maybe put it into desktop?





------------------ Original ------------------
From: abhovi ***@***.***&gt;
Date: Fri,Aug 2,2024 6:35 PM
To: derekhe/xplane-map-enhancement-release ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/xplane-map-enhancement-release] Welcome toxplane-map-enhancement-release Discussions! (Issue #41)

**Comment by abhovi** [comment]
I did. Same Error.

**Comment by derekhe** [comment]
I have no idea. Could you paste some screenshots for video?

**Comment by abhovi** [comment]
First I want to express my appreciation for the fact that you really react to my little problem. Thank you for that.
As for your requatd for images: there is very little to show: as soon as I have downloaded your program, I get the usual warnings, and after ignoring them all I get the opportunity to activate the installation. No way, I simply get the immediate screen with the denial. I am tinkering with flightsimulators for over 30 years, but never experienced this.

![Schermafbeelding 2024-08-03 074356](https://github.com/user-attachments/assets/a7ba696e-06f6-4ec9-a980-0b5ded2e1526)
![Schermafbeelding 2024-08-03 074429](https://github.com/user-attachments/assets/9b9b4584-ed0b-40f3-9759-901b4ecafe2d)
![Schermafbeelding 2024-08-03 074453](https://github.com/user-attachments/assets/fa726bc9-9fda-4c2f-b023-4557eaa26657)
![Schermafbeelding 2024-08-03 075433](https://github.com/user-attachments/assets/75587223-3ba0-44ee-b88d-a19b8e276e24)

The last screenshot is only to show that I hardly use my gamer for more than just flightsims.
My system is AMD Ryzen 7 3700X 8-core processor
RAM 32 Gb
Windows 11 updated
NVidia GeForce RTX 3070

Thanks again for your attention.

Ab

**Comment by derekhe** [comment]
I googled "inno setup unable to execute file in the temporary directory" and find these solutions you can try:
https://answers.microsoft.com/en-us/windows/forum/all/unable-to-execute-files-in-the-temporary-directory/0d441663-6167-420d-b936-53f9c3d17898
https://www.partitionwizard.com/clone-disk/unable-to-execute-file-in-temporary-directory.html
https://answers.microsoft.com/en-us/windows/forum/all/unable-to-create-temporary-files-setup-aborted/75348e82-9a39-4eb7-9600-06e9265a9fef

**Comment by abhovi** [comment]
Thank you again.
I tried all the options mentioned. Nothing works, except that in the new Temp folder there is an extra file, containing almost nothing:

![Schermafbeelding 2024-08-03 093140](https://github.com/user-attachments/assets/bb9b2dc4-7f1c-44ef-a0fb-4754008943ec)
![Schermafbeelding 2024-08-03 093156](https://github.com/user-attachments/assets/1ee763db-9c93-497a-b05f-747dd9006b6a)
![Schermafbeelding 2024-08-03 093244](https://github.com/user-attachments/assets/f08a8dc1-7214-4c22-87fc-fa7b111dade4)

I think this is way beyond my computer capacities. I will turn to a professional.
Thank you for your help, sorry to have bothered you with my minor problems.
Ab
