### ISSUE TITLE
extremely slow extraction process

### ISSUE THREAD

**Issue by wildsam123** [derekhe/xplane-map-enhancement-release#5]
Using the exe provided for the extraction of each sector, extraction goes well up till terrain files where the download speed tanks heavily from MBs to KBs within hours or minutes and goes even as low as 250 KB/s. Others claim this isnt an issue for them but it is for me and i believe it might be affecting others too.
Version: 0.9.3
Platform: Windows 11 (64-Bit)
Computer specification: Operating System
	Windows 11 Pro 64-bit
CPU
	Intel Core i5 3470 @ 3.20GHz	51 °C
	Ivy Bridge 22nm Technology
RAM
	12.0GB Dual-Channel DDR3 @ 798MHz (11-11-11-28)
Motherboard
	Dell Inc. 0GY6Y8 (CPU 1)
Graphics
	DELL P2419H (1920x1080@60Hz)
	4095MB NVIDIA GeForce GTX 1050 Ti (MSI)	43 °C

**Comment by derekhe** [comment]
Yes, it is very slow at the moment. I'm working on a way to optimize it.
Don't put the files into HDD which make it even slower.
