### ISSUE TITLE
"The game is running" but it is not....Cannot get mapping to start anymore!!

### ISSUE THREAD

**Issue by DxMarovitch** [derekhe/xplane-map-enhancement-release#51]
## Bug Feedback

**Required:**

* **Title:** "The game is running. This MOD must run before the game is running, otherwise it may not work properly.
* **Description:** This happened earlier when I closed XP12 and then went to close XPMapEnhancement, like I normally do, and XPMapEnhancement said that XP was still running. It was not, I even checked in task manager. So now when I start XPMapEnhancement it says that XP is still running, and I am not able to successfully click the Start button. I have tried restarting my PC, and even reinstalling XPMapEnhancement. I also tried deleting the Users/(my username)/Appdata/Roaming/XPMapEnhancement folder and completely starting from new settings, and it STILL says XP is running. But it is not. I don't know what to do, and now I cannot use the program anymore, which makes me very sad =[ You can reach me on Discord at DxMarovitch or by email at Tuffo3 (at) gmail.com - Thank you!
* **Version:** 2.0.3 (latest!)
* **Platform:** PC, Windows 11, XP12
* **Screenshots:** (If applicable)
![image](https://github.com/user-attachments/assets/e1ef9f42-1aff-4e14-8d12-a5698097a773)

**Thank you for your help!**

**Comment by derekhe** [comment]
It get process name contains "X-Plane", please check if any process has this name.

**Comment by DxMarovitch** [comment]
Nothing showing in Task Manager or Process Lasso, I got Process Explorer opened up and I see this:

![image](https://github.com/user-attachments/assets/ae79b4b2-8598-470f-b957-24fcface3c95)

When I try to Kill Process, I get this:

![image](https://github.com/user-attachments/assets/2af528c6-84d0-4c7c-b786-022a598d9627)

What the hell? This process is even there after I restart my computer....?!

**Comment by DxMarovitch** [comment]
Actually, I did just think of something: Yesterday I updated XP12 to the latest beta. I wonder, if the latest beta is causing this issue!

**Comment by DxMarovitch** [comment]
Okay, I just got home from work, and restarted my PC again. I immediately ran Process Explorer and looked for this strange ghost X-Plane.exe, and it was not there. So I immediately started XPMapEnhancement and was able to get it to start.

With that being said, all seems well....That was just very strange. I suppose if it happens again I can just repeat this process to get XPMapEnhancement to work.

**Comment by DxMarovitch** [comment]
Using XP12 again today and did not have the problem, going to close this issue. Not sure what was going on before....Very strange....

Anyhow thank you for the initial response trying to help =]

Dan
