### ISSUE TITLE
Enhance the pre-loaded distance

### ISSUE THREAD

**Issue by Marci353** [derekhe/xplane-map-enhancement-release#53]
Thank you very-very much for this wonderful add-on!!! A sim changer! Inmediately subscribed to the pro version.

I have only one suggestion: the preload function allows preloading the tiles from about 10 nm distance around the aircraft. Could you make it more than 10 nm? Or better: build in a slider, where the user can set that distance. Because it can be bigger if you have a strong computer, as I have, and if I could set it to 50 nm for ex., I wouldnt see any missing/not yet loaded tiles or gap in the distance.

Would it be possible?

**Comment by derekhe** [comment]
Yes, it is adjustable. I think I can provide a slider in next release.

**Comment by Marci353** [comment]
Fantastic!Thank you!--Sent from my Android phone.On 2024. 09. 03., 14:05 hesicong ***@***.***> wrote:

  
  Yes, it is adjustable. I think I can provide a slider in next release.

**Comment by Marci353** [comment]
Just downloaded the newest version, the slider is not yet there. Will you still provide it? Thx

**Comment by derekhe** [comment]
@Marci353 it is in the app now.

**Comment by derekhe** [comment]
https://github.com/derekhe/xplane-map-enhancement-release/releases/tag/2.0.7

**Comment by Marci353** [comment]
Great, thank you!

One question: we can now set the distance AHEAD. But what about WIDE? It is still only 2nm?

**Comment by derekhe** [comment]
Yes, it is ahead. I think I can also set the width later.

**Comment by Marci353** [comment]
Thanks, that would be very useful, and would make sense.

**Comment by derekhe** [comment]
@Marci353  please check 2.0.9, you can set the distance and width now.
