### ISSUE TITLE
Check .NET Version

### ISSUE THREAD

**Issue by Fragtality** [derekhe/xplane-map-enhancement-release#54]
## Bug Feedback

**Help us improve!** Report bugs you encounter using this template:

**Required:**

* **Title:** .NET Runtime is installed although it is already installed in the given or even new Version
* **Description:** Installer for .NET Runtime is only executed when needed
* **Version:** latest
* **Platform:** Windows 10
* **Computer specification:**
* **Screenshots:** 

**Optional:**

I did this myself for the Apps I'm developing, so your more than welcome to get some Inspiration from my [Code ](https://github.com/Fragtality/PilotsDeck/blob/master/Installer/InstallerFunctions.cs#L492)(if needed at all) 😃

**Comment by Fragtality** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

I think you are in the wrong Issue or even Repo ...

**Comment by derekhe** [comment]
Cool, thanks. You even build an installer :)

**Comment by Fragtality** [comment]
Don't know why this was closed - it still doesn't check the Version, it still installs .NET although already installed.
Besides that: 8.0.7 is outdated.

And another Idea: Please run the downloaded Updated. It is a bit cumbersome to first close XME, then start it again, then close it again to get the Update/Installer going ;)
