### ISSUE TITLE
20mn to launch xplane with XPLANE ME

### ISSUE THREAD

**Issue by Alamasse1** [derekhe/xplane-map-enhancement-release#64]
## Bug Feedback
Hi
I have to wait 20mn to launch XP in free version. I imagine that it was thé first launching desagrement.  But no, it is for each time. 
What i miss ?

* **Description:** What did you expect? What happened instead? (Include screenshots/recordings if possible)
* **Version:** (If applicable)
* **Platform:** (If applicable)
* **Computer specification:**
* **Screenshots:** (If applicable)

**Optional:**

* Any additional helpful information.

**Note:** This is for bug reports only. For general feedback, use the [appropriate channel].

**Thank you for your help!**

**---**

**Tips:**

* Be clear and concise.
* Be specific about steps and behavior.
* Check for existing issues before reporting new ones.

Following these guidelines helps us fix bugs faster.

**Comment by derekhe** [comment]
Please have a look: https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN#34-slow-map-loading

**Comment by derekhe** [comment]
Fixed in: https://github.com/derekhe/xplane-map-enhancement-release/releases/tag/2.0.12

**Comment by Alamasse1** [comment]
G‌reat ameliorations!
Thank you
 

De : "hesicong" ***@***.***>
A : "derekhe/xplane-map-enhancement-release" ***@***.***>,"Alamasse1" ***@***.***>,"Author" ***@***.***>
Envoyé: mardi 29 Octobre 2024 14:59
Objet : Re: [derekhe/xplane-map-enhancement-release] 20mn to launch xplane with XPLANE ME (Issue #64)
 

 

Fixed in: https://github.com/derekhe/xplane-map-enhancement-release/releases/tag/2.0.12
