### ISSUE TITLE
Infinite Loading in time and size

### ISSUE THREAD

**Issue by ator84** [derekhe/xplane-map-enhancement-release#65]
The problem I have is that when I start the map enhancement version 2.0.11.0 with X-Plane 12.1.2 the loading time is infinite (10 minutes or more). Basically until the cache is full (30 GB) the sim doesn't finish the loading process. I checked what I have in the cache folder after and what I saw is that every tile was doubled (the first copy is 4096X4096 and then the other one is 256X256 even if I set up the image quality to high). I asked other friends that also have map enhancement and their sim loads after only 2/3 minutes and inside their cache folder they only have one copy of each file (512X512 as their image is also set to high quality) and their sim also satrts up only after loading 10.000 tiles; mine as already said starts up after loading almost 500.000 tiles in 10 or more minutes. See screenshots.

Device ID: 5PDSBG54M507FSVF2QBR9YPRHTQR04X5HV1DHARJFCJH2M1W0AD0

![image](https://github.com/user-attachments/assets/659a9d17-883a-49d7-be29-f6cbcfcae4ef)
![image](https://github.com/user-attachments/assets/b610edfc-2cf6-4278-882c-28c045fc7dd0)

**Comment by derekhe** [comment]
I have another friend and he also has this similar issue. It seems something in XPlane asks for high quality images which is very far away from the airport. This is why you see the same image have different resolution.
I spent several days comparing our XPlane setup (from graphic settings, plugins, custom sceneries), we tried everything but still the same.
To fix this problem, you can try "Fast load" option in the setting page. The downside is the satellite images around airport will be blurry, but once you leave the ground, it will load HD images. https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN#34-slow-map-loading

**Comment by derekhe** [comment]
If you have found any clue or thought about something may cause this issue, please let me know.

**Comment by ator84** [comment]
Is your friend also using Windows 10? Because I am the only one with Windows 10 instead all my friends have Windows 11. Maybe is a coincidence but it is worth to ask?

**Comment by ator84** [comment]
> If you have found any clue or thought about something may cause this issue, please let me know.

I solved installing a different antivirus, in particular Bitdefender. Previously I was using Windows default antivirus and even by activating the exclusions the issue was still there. After installing the new antivirus all was solved.  Hope it will be helpful. 
PS: Bitdefender has a 30 days trial so you can try if it works without having to pay something.

**Comment by derekhe** [comment]
Thanks for the investigation, we tried and it really the MSFS defender's issue. On my development machine I have another antivirus software installed so I can't reproduce the issue. I will try to have a look how to prevent the defender affect this mod.

**Comment by derekhe** [comment]
I tried defender and this problem reproduced.

**Comment by derekhe** [comment]
https://github.com/derekhe/xplane-map-enhancement-release/releases/tag/2.0.12
