### ISSUE TITLE
"Restart to repair drive errors"

### ISSUE THREAD

**Issue by Marci353** [derekhe/xplane-map-enhancement-release#66]
Since yesterday I have this message appearing when starting XPMapEnh.:

Restart to repair drive errors - 
click to restart your PC.

I did not change anything, not downloaded anything. Suddenly this message appeared.

It is most likely the virtual drives created by XPMapEnh. 

![2](https://github.com/user-attachments/assets/06f4975a-082e-4804-be9f-c955c41690e0)

**Comment by derekhe** [comment]
I have no idea about this error. I didn't see other users report this issue.
Please check if the vhd file is corrupted.

**Comment by Marci353** [comment]
If i click the download in the app, it says all the files are downloaded. From XPMapEnh no error report coming.

Is there any other way to check if the vhd file is corrupted?

**Comment by derekhe** [comment]
You can try mount the vhd file: https://www.elevenforum.com/t/mount-or-unmount-vhd-and-vhdx-file-as-drive-in-windows-11.19177/

**Comment by Marci353** [comment]
Help me a bit, please. 

1., In Disk Management (diskmgmt.msc) it is clearly visible that the virtual volumes/drives are mounted. But if I go to properties, and try to check drive, nothing happens.

2., Even if as described above, in Windows Explorer the virtual drives are not visible. See pictures.
![3](https://github.com/user-attachments/assets/acbb00d9-928a-4ff1-920a-2daf631c4212)
![4](https://github.com/user-attachments/assets/ae392e72-2343-4b60-bf1d-790da37bf2a5)

**Comment by Marci353** [comment]
Please, delete this whole issue.

The culprit was a file corruption on my side.

Thanks
