### ISSUE TITLE
Using yOrtho4XP_Overlays possible?

### ISSUE THREAD

**Issue by Marci353** [derekhe/xplane-map-enhancement-release#67]
Not a bug, just a question, I found nowhere an answer to it. So:

In the Wiki, you are writing: "...yAutoOrtho_Overlays: Satellite map package If you have installed SimHeaven, do not download yAutoOrtho_Overlays, as it will cause trees on runways. We strongly recommend installing SimHeaven...."

But what if I have yOrtho4XP_Overlays for the whole world? Can I use it instead of yAutoOrtho_Overlays?

(I dont use SimHeaven)

Thanks for your answer.

**Comment by derekhe** [comment]
I don't know. You can have a try :)

**Comment by Marci353** [comment]
I will.

By the way, what is the source of your yAutoOrtho_Overlyays?

Because ortho4XPOverlays' source is mostly XPlane Global Scenery.

**Comment by derekhe** [comment]
It is coming from AutoOrtho and I modified it.
