### ISSUE TITLE
License link fails

### ISSUE THREAD

**Issue by Alamasse1** [derekhe/xplane-map-enhancement-release#71]
## Bug Feedback

suddently my license is not operative.
I did not link my license in an another device
![Capture d'écran 2024-11-08 180912](https://github.com/user-attachments/assets/ada4cddd-277d-459b-826e-7c66b7ca4dd8)
Help!!

**Required:**

* **Title:** Briefly describe the bug.
* **Description:** What did you expect? What happened instead? (Include screenshots/recordings if possible)
* **Version:** (If applicable)
* **Platform:** (If applicable)
* **Computer specification:**
* **Screenshots:** (If applicable)

**Optional:**

* Any additional helpful information.

**Note:** This is for bug reports only. For general feedback, use the [appropriate channel].

**Thank you for your help!**

**---**

**Tips:**

* Be clear and concise.
* Be specific about steps and behavior.
* Check for existing issues before reporting new ones.

Following these guidelines helps us fix bugs faster.

**Comment by derekhe** [comment]
Please try again and it should work now. I will delete this thread as it contains personal information.
