### ISSUE TITLE
Settings are not being saved across runs

### ISSUE THREAD

**Issue by hakasapl** [derekhe/xplane-map-enhancement-release#79]
* **Title:** Settings are not being saved across runs
* **Description:** Every time I open xplane map enhancement I get the message about first time opening and that I need to set paths. After setting paths and closing it is not saved. Upon reopening I get the same message with default settings.
* **Version:** 2.0.14.0
* **Platform:** Windows
* **Computer specification:** i9 12900k / RTX 3090
* **Screenshots:** N/A

**Comment by derekhe** [comment]
I will investigate.

**Comment by derekhe** [comment]
Please try latest version
