### ISSUE TITLE
Seasons support?

### ISSUE THREAD

**Issue by GiacomoC00** [derekhe/xplane-map-enhancement-release#88]
Does map enhancement support X-Plane Seasons and snow depiction on ground?

**Comment by derekhe** [comment]
It supports snow colour. But the satellite images won't change like MSFS2024.

**Comment by GiacomoC00** [comment]
@derekhe ok with autoortho I have snow on ground but with map enhancement it seems that snow covers only roads. (see image). Is this normal? Can we have the same integration that there is with autoortho? Thank you.
![Screenshot 2024-12-14 120821](https://github.com/user-attachments/assets/f66c5ef0-4953-4798-ab82-0084b694aa2d)

**Comment by derekhe** [comment]
Autoortho doesn't do anything about seasons, so does this app. The season is controlled by game itself. You can change the weather in the game to get more snows. Try different places and maps.

**Comment by GiacomoC00** [comment]
@derekhe I can guarantee you that with autoortho if you go for example to EFRO you have snow on the ground but with map enhancement in the same place with same weather you have what you see in the photo, snow ONLY on the roads.
